[build]
builder = "NIXPACKS"
buildCommand = "export PORT=8080 && npm install && npx prisma generate --schema=./schema.prisma"

[deploy]
startCommand = "npx prisma migrate deploy --schema=./schema.prisma && node prisma/seed.js && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
