/**
 * reports.js  – v2.2
 *
 * New in this version:
 *  ┌──────────────────────────────────────────────────────────────────────────┐
 *  │  GET  /reports/group/performance     Group performance dashboard          │
 *  │  GET  /reports/group/hotel-compare   Side-by-side hotel comparison        │
 *  │  GET  /reports/group/revenue-trend   Revenue trend across all hotels      │
 *  │  GET  /reports/group/staff-activity  Staff & role activity summary        │
 *  │                                                                            │
 *  │  GET  /reports/export/excel?type=... Custom date range on ALL exports      │
 *  │  GET  /reports/export/pdf?type=...   Branded PDF export (ALL report types) │
 *  └──────────────────────────────────────────────────────────────────────────┘
 *
 *  Custom date range: pass ?startDate=YYYY-MM-DD&endDate=YYYY-MM-DD on any
 *  endpoint, or use the ?period= shorthand (today|week|month|year).
 *
 *  Branded authentication on exports:
 *   - Every exported file (Excel or PDF) embeds: generated by, role, hotel/group
 *     name, and timestamp so the export is self-authenticating.
 *   - PDF cover page shows group logo placeholder, report title, period, and
 *     "Powered by Anchor Hotel Suite".
 *   - Excel workbook properties carry creator, company, and generated-at.
 */

import express        from 'express';
import ExcelJS        from 'exceljs';
import PDFDocument    from 'pdfkit';
import prisma         from './prisma.js';
import { authenticate, requireLevel } from './middleware.js';

const router = express.Router();

// ═══════════════════════════════════════════════════════════════════════════════
// COLOURS (shared across PDF builder)
// ═══════════════════════════════════════════════════════════════════════════════
const C = {
  navy:   '#1A3A5C',
  teal:   '#0D9488',
  lgrey:  '#F1F5F9',
  mgrey:  '#94A3B8',
  dgrey:  '#334155',
  white:  '#FFFFFF',
  green:  '#16A34A',
  red:    '#DC2626',
  amber:  '#D97706',
};

// ═══════════════════════════════════════════════════════════════════════════════
// SCOPE HELPERS
// ═══════════════════════════════════════════════════════════════════════════════

/** Return the hotel IDs the requesting user is allowed to query. */
async function resolveHotelScope(user, queryHotelId) {
  if (user.role === 'SUPER_ADMIN') {
    if (queryHotelId) return [queryHotelId];
    const all = await prisma.hotel.findMany({ select: { id: true } });
    return all.map((h) => h.id);
  }
  if (user.role === 'GROUP_MANAGER') {
    const hotels = await prisma.hotel.findMany({
      where: { groupId: user.groupId, ...(queryHotelId ? { id: queryHotelId } : {}) },
      select: { id: true },
    });
    return hotels.map((h) => h.id);
  }
  // GENERAL_MANAGER and below
  return [user.hotelId];
}

/** Resolve the group ID the user belongs to. */
function resolveGroupId(user, queryGroupId) {
  if (user.role === 'SUPER_ADMIN') return queryGroupId || null;
  return user.groupId || null;
}

function resolvePeriod(period, startDate, endDate) {
  const now = new Date();
  if (startDate && endDate) {
    return {
      start: new Date(startDate + 'T00:00:00.000Z'),
      end:   new Date(endDate   + 'T23:59:59.999Z'),
    };
  }
  switch (period) {
    case 'today':
      return {
        start: new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())),
        end:   new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), 23, 59, 59, 999)),
      };
    case 'week': {
      const d = new Date(now); d.setUTCDate(d.getUTCDate() - 7);
      return { start: d, end: now };
    }
    case 'year':
      return {
        start: new Date(Date.UTC(now.getUTCFullYear(), 0, 1)),
        end:   new Date(Date.UTC(now.getUTCFullYear(), 11, 31, 23, 59, 59, 999)),
      };
    case 'quarter': {
      const q = Math.floor(now.getUTCMonth() / 3);
      return {
        start: new Date(Date.UTC(now.getUTCFullYear(), q * 3, 1)),
        end:   new Date(Date.UTC(now.getUTCFullYear(), q * 3 + 3, 0, 23, 59, 59, 999)),
      };
    }
    case 'month':
    default:
      return {
        start: new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)),
        end:   new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 0, 23, 59, 59, 999)),
      };
  }
}

function formatDateKey(date, groupBy) {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, '0');
  const d = String(date.getUTCDate()).padStart(2, '0');
  if (groupBy === 'month') return `${y}-${m}`;
  if (groupBy === 'year')  return `${y}`;
  return `${y}-${m}-${d}`;
}

const fmtNGN = (v) => `NGN ${Number(v || 0).toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;

// ═══════════════════════════════════════════════════════════════════════════════
// ── EXISTING REPORTS (preserved + custom date range) ──────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

// GET /reports/financial
router.get('/financial', authenticate, requireLevel(7), async (req, res) => {
  try {
    const { hotelId, period, startDate, endDate, groupBy = 'day' } = req.query;
    const hotelIds = await resolveHotelScope(req.user, hotelId);
    const { start, end } = resolvePeriod(period, startDate, endDate);

    const where = { hotelId: { in: hotelIds }, createdAt: { gte: start, lte: end } };

    const [income, expenses, transactions] = await Promise.all([
      prisma.transaction.aggregate({ where: { ...where, type: 'INCOME'  }, _sum: { amount: true } }),
      prisma.transaction.aggregate({ where: { ...where, type: 'EXPENSE' }, _sum: { amount: true } }),
      prisma.transaction.findMany({ where, orderBy: { createdAt: 'asc' } }),
    ]);

    const byCategory = {};
    const byDate     = {};
    transactions.forEach((t) => {
      if (!byCategory[t.category]) byCategory[t.category] = { income: 0, expense: 0 };
      if (t.type === 'INCOME') byCategory[t.category].income += Number(t.amount);
      else                      byCategory[t.category].expense += Number(t.amount);

      const key = formatDateKey(new Date(t.createdAt), groupBy);
      if (!byDate[key]) byDate[key] = { income: 0, expense: 0, net: 0 };
      if (t.type === 'INCOME') byDate[key].income += Number(t.amount);
      else                      byDate[key].expense += Number(t.amount);
      byDate[key].net = byDate[key].income - byDate[key].expense;
    });

    const totalIncome   = Number(income._sum.amount || 0);
    const totalExpenses = Number(expenses._sum.amount || 0);

    res.json({
      period: { start, end },
      summary: { totalIncome, totalExpenses, netRevenue: totalIncome - totalExpenses, transactionCount: transactions.length },
      byCategory,
      byDate: Object.entries(byDate).map(([date, vals]) => ({ date, ...vals })),
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to generate financial report' });
  }
});

// GET /reports/occupancy
router.get('/occupancy', authenticate, requireLevel(7), async (req, res) => {
  try {
    const { hotelId, period, startDate, endDate } = req.query;
    const hotelIds = await resolveHotelScope(req.user, hotelId);
    const { start, end } = resolvePeriod(period, startDate, endDate);

    const where = { hotelId: { in: hotelIds }, createdAt: { gte: start, lte: end } };

    const [checkIns, checkOuts, totalNights, avgRev] = await Promise.all([
      prisma.roomLog.count({ where: { ...where, status: { not: 'CANCELLED' } } }),
      prisma.roomLog.count({ where: { ...where, status: 'CHECKED_OUT' } }),
      prisma.roomLog.aggregate({ where: { ...where, status: { not: 'CANCELLED' } }, _sum: { nights: true } }),
      prisma.roomLog.aggregate({ where: { ...where, status: { not: 'CANCELLED' } }, _avg: { totalAmount: true } }),
    ]);

    res.json({
      period: { start, end },
      checkIns, checkOuts,
      totalNights: Number(totalNights._sum.nights || 0),
      avgNightsPerBooking: checkIns > 0
        ? Math.round((Number(totalNights._sum.nights || 0) / checkIns) * 10) / 10 : 0,
      avgRevenuePerBooking: Math.round(Number(avgRev._avg.totalAmount || 0)),
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to generate occupancy report' });
  }
});

// GET /reports/monthly-balance
router.get('/monthly-balance', authenticate, requireLevel(7), async (req, res) => {
  try {
    const { hotelId, year } = req.query;
    const hotelIds    = await resolveHotelScope(req.user, hotelId);
    const targetYear  = parseInt(year) || new Date().getUTCFullYear();

    const months = [];
    for (let month = 0; month < 12; month++) {
      const start = new Date(Date.UTC(targetYear, month, 1));
      const end   = new Date(Date.UTC(targetYear, month + 1, 0, 23, 59, 59, 999));
      const where = { hotelId: { in: hotelIds }, createdAt: { gte: start, lte: end } };
      const [inc, exp] = await Promise.all([
        prisma.transaction.aggregate({ where: { ...where, type: 'INCOME'  }, _sum: { amount: true } }),
        prisma.transaction.aggregate({ where: { ...where, type: 'EXPENSE' }, _sum: { amount: true } }),
      ]);
      const totalIncome  = Number(inc._sum.amount || 0);
      const totalExpense = Number(exp._sum.amount || 0);
      months.push({
        month: month + 1,
        monthName: new Date(Date.UTC(targetYear, month, 1)).toLocaleString('en', { month: 'long' }),
        totalIncome, totalExpense, netBalance: totalIncome - totalExpense,
      });
    }
    const yearTotal = months.reduce(
      (a, m) => ({ income: a.income + m.totalIncome, expense: a.expense + m.totalExpense, net: a.net + m.netBalance }),
      { income: 0, expense: 0, net: 0 }
    );
    res.json({ year: targetYear, months, yearTotal });
  } catch (err) {
    res.status(500).json({ error: 'Failed to generate balance sheet' });
  }
});

// GET /reports/pos-summary
router.get('/pos-summary', authenticate, requireLevel(3), async (req, res) => {
  try {
    const { hotelId, period, startDate, endDate } = req.query;
    const hotelIds = await resolveHotelScope(req.user, hotelId);
    const { start, end } = resolvePeriod(period, startDate, endDate);
    const where = { hotelId: { in: hotelIds }, createdAt: { gte: start, lte: end } };

    const [total, byPayment, topItems] = await Promise.all([
      prisma.pOSSale.aggregate({ where, _sum: { totalAmount: true }, _count: true }),
      prisma.pOSSale.groupBy({ by: ['paymentType'], where, _sum: { totalAmount: true }, _count: true }),
      prisma.pOSSaleItem.groupBy({
        by: ['name', 'category'],
        where: { sale: where },
        _sum: { totalPrice: true, quantity: true },
        orderBy: { _sum: { totalPrice: 'desc' } },
        take: 10,
      }),
    ]);

    res.json({
      period: { start, end },
      totalRevenue: Number(total._sum.totalAmount || 0),
      totalTransactions: total._count,
      byPaymentType: byPayment,
      topItems,
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to generate POS summary' });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// ── GROUP PERFORMANCE REPORTS  (level 8 = GROUP_MANAGER+) ─────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * GET /reports/group/performance
 * Top-level KPI dashboard for a group: revenue, occupancy, POS, expenses
 * broken down per hotel subsidiary, with group-wide totals.
 *
 * Query: ?groupId=&period=&startDate=&endDate=
 */
router.get('/group/performance', authenticate, requireLevel(8), async (req, res) => {
  try {
    const { period, startDate, endDate } = req.query;
    const groupId  = resolveGroupId(req.user, req.query.groupId);
    const { start, end } = resolvePeriod(period, startDate, endDate);

    // Fetch all hotels in this group
    const hotels = await prisma.hotel.findMany({
      where: { ...(groupId ? { groupId } : {}), isActive: true },
      select: { id: true, name: true, currency: true, _count: { select: { rooms: true, users: true } } },
      orderBy: { name: 'asc' },
    });

    const hotelIds = hotels.map((h) => h.id);
    const dateRange = { gte: start, lte: end };

    // Parallel fetch across all hotels
    const [
      incomeAgg, expenseAgg,
      checkIns, checkOuts,
      nightsAgg, posAgg,
      maintenanceOpen, activeStaff,
    ] = await Promise.all([
      prisma.transaction.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, type: 'INCOME',  createdAt: dateRange },
        _sum: { amount: true },
      }),
      prisma.transaction.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, type: 'EXPENSE', createdAt: dateRange },
        _sum: { amount: true },
      }),
      prisma.roomLog.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, status: { not: 'CANCELLED' }, createdAt: dateRange },
        _count: true,
      }),
      prisma.roomLog.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, status: 'CHECKED_OUT', createdAt: dateRange },
        _count: true,
      }),
      prisma.roomLog.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, status: { not: 'CANCELLED' }, createdAt: dateRange },
        _sum: { nights: true },
      }),
      prisma.pOSSale.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, createdAt: dateRange },
        _sum: { totalAmount: true },
        _count: true,
      }),
      prisma.maintenanceLog.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, status: { in: ['OPEN', 'IN_PROGRESS'] } },
        _count: true,
      }),
      prisma.user.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, isVerified: true },
        _count: true,
      }),
    ]);

    // Index by hotelId for O(1) lookup
    const idx = (arr, key = 'hotelId') => Object.fromEntries(arr.map((r) => [r[key], r]));
    const incIdx  = idx(incomeAgg);
    const expIdx  = idx(expenseAgg);
    const ciIdx   = idx(checkIns);
    const coIdx   = idx(checkOuts);
    const nIdx    = idx(nightsAgg);
    const posIdx  = idx(posAgg);
    const maintIdx= idx(maintenanceOpen);
    const staffIdx= idx(activeStaff);

    const hotelStats = hotels.map((h) => {
      const income      = Number(incIdx[h.id]?._sum?.amount  || 0);
      const expense     = Number(expIdx[h.id]?._sum?.amount  || 0);
      const posRevenue  = Number(posIdx[h.id]?._sum?.totalAmount || 0);
      const totalNights = Number(nIdx[h.id]?._sum?.nights   || 0);
      const checkInCount= ciIdx[h.id]?._count || 0;
      const checkOutCount=coIdx[h.id]?._count || 0;
      const totalRooms  = h._count.rooms;
      const occupancyRate = totalRooms > 0 && totalNights > 0
        ? Math.min(100, Math.round((totalNights / (totalRooms * 30)) * 100)) : 0;

      return {
        hotelId:       h.id,
        hotelName:     h.name,
        totalRooms,
        staffCount:    staffIdx[h.id]?._count || 0,
        revenue: {
          accommodation: income - posRevenue,
          pos:           posRevenue,
          total:         income,
        },
        expenses:      expense,
        netProfit:     income - expense,
        occupancy: {
          checkIns:   checkInCount,
          checkOuts:  checkOutCount,
          totalNights,
          occupancyRate,
        },
        pos: {
          totalRevenue:    posRevenue,
          transactionCount: posIdx[h.id]?._count || 0,
        },
        openMaintenanceIssues: maintIdx[h.id]?._count || 0,
      };
    });

    // Group-wide totals
    const groupTotals = hotelStats.reduce(
      (acc, h) => ({
        totalRevenue:    acc.totalRevenue    + h.revenue.total,
        totalExpenses:   acc.totalExpenses   + h.expenses,
        netProfit:       acc.netProfit       + h.netProfit,
        totalCheckIns:   acc.totalCheckIns   + h.occupancy.checkIns,
        totalNights:     acc.totalNights     + h.occupancy.totalNights,
        totalPOSRevenue: acc.totalPOSRevenue + h.pos.totalRevenue,
        openMaintenance: acc.openMaintenance + h.openMaintenanceIssues,
      }),
      { totalRevenue: 0, totalExpenses: 0, netProfit: 0,
        totalCheckIns: 0, totalNights: 0, totalPOSRevenue: 0, openMaintenance: 0 }
    );

    // Best & worst performers
    const sorted      = [...hotelStats].sort((a, b) => b.revenue.total - a.revenue.total);
    const topHotel    = sorted[0]   || null;
    const bottomHotel = sorted[sorted.length - 1] || null;

    res.json({
      period: { start, end },
      groupId,
      groupTotals,
      hotels: hotelStats,
      insights: {
        topPerformer:    topHotel    ? { id: topHotel.hotelId,    name: topHotel.hotelName,    revenue: topHotel.revenue.total }    : null,
        bottomPerformer: bottomHotel ? { id: bottomHotel.hotelId, name: bottomHotel.hotelName, revenue: bottomHotel.revenue.total } : null,
        avgOccupancyRate: hotelStats.length
          ? Math.round(hotelStats.reduce((s, h) => s + h.occupancy.occupancyRate, 0) / hotelStats.length) : 0,
      },
    });
  } catch (err) {
    console.error('Group performance error:', err);
    res.status(500).json({ error: 'Failed to generate group performance report' });
  }
});

/**
 * GET /reports/group/hotel-compare
 * Side-by-side comparison table of key metrics across all hotels in a group.
 * Useful for spotting outliers and benchmarking.
 */
router.get('/group/hotel-compare', authenticate, requireLevel(8), async (req, res) => {
  try {
    const { period, startDate, endDate } = req.query;
    const groupId  = resolveGroupId(req.user, req.query.groupId);
    const { start, end } = resolvePeriod(period, startDate, endDate);

    const hotels  = await prisma.hotel.findMany({
      where: { ...(groupId ? { groupId } : {}), isActive: true },
      select: { id: true, name: true, totalRooms: true, maxStaff: true, vatPercent: true },
      orderBy: { name: 'asc' },
    });
    const hotelIds = hotels.map((h) => h.id);
    const dateRange = { gte: start, lte: end };

    const [revenue, costs, bookings, posRev, expenses] = await Promise.all([
      prisma.transaction.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, type: 'INCOME', createdAt: dateRange },
        _sum: { amount: true },
      }),
      prisma.transaction.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, type: 'EXPENSE', createdAt: dateRange },
        _sum: { amount: true },
      }),
      prisma.roomLog.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, status: { not: 'CANCELLED' }, createdAt: dateRange },
        _count: true,
        _avg:  { totalAmount: true, nights: true },
        _sum:  { nights: true },
      }),
      prisma.pOSSale.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, createdAt: dateRange },
        _sum: { totalAmount: true },
        _count: true,
      }),
      prisma.expense.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, status: 'APPROVED', createdAt: dateRange },
        _sum: { amount: true },
        _count: true,
      }),
    ]);

    const ri = Object.fromEntries(revenue.map((r) => [r.hotelId, r]));
    const ci = Object.fromEntries(costs.map((r) => [r.hotelId, r]));
    const bi = Object.fromEntries(bookings.map((r) => [r.hotelId, r]));
    const pi = Object.fromEntries(posRev.map((r) => [r.hotelId, r]));
    const ei = Object.fromEntries(expenses.map((r) => [r.hotelId, r]));

    const comparison = hotels.map((h) => {
      const rev      = Number(ri[h.id]?._sum?.amount || 0);
      const cost     = Number(ci[h.id]?._sum?.amount || 0);
      const nights   = Number(bi[h.id]?._sum?.nights || 0);
      const bookingCount = bi[h.id]?._count || 0;
      const pos      = Number(pi[h.id]?._sum?.totalAmount || 0);

      return {
        hotelId:           h.id,
        hotelName:         h.name,
        totalRooms:        h.totalRooms,
        vatPercent:        Number(h.vatPercent),
        totalRevenue:      rev,
        totalCosts:        cost,
        grossMargin:       rev > 0 ? Math.round(((rev - cost) / rev) * 100) : 0,
        netProfit:         rev - cost,
        bookings:          bookingCount,
        totalNights:       nights,
        avgStayNights:     bookingCount > 0 ? Math.round((nights / bookingCount) * 10) / 10 : 0,
        avgBookingValue:   bookingCount > 0 ? Math.round(Number(bi[h.id]?._avg?.totalAmount || 0)) : 0,
        occupancyRate:     h.totalRooms > 0 && nights > 0
                           ? Math.min(100, Math.round((nights / (h.totalRooms * 30)) * 100)) : 0,
        posRevenue:        pos,
        posSalesCount:     pi[h.id]?._count || 0,
        approvedExpenses:  Number(ei[h.id]?._sum?.amount || 0),
        expenseCount:      ei[h.id]?._count || 0,
        revPerRoom:        h.totalRooms > 0 ? Math.round(rev / h.totalRooms) : 0,
      };
    });

    // Rankings
    const ranked = {
      byRevenue:     [...comparison].sort((a, b) => b.totalRevenue - a.totalRevenue).map((h, i) => ({ rank: i + 1, hotelId: h.hotelId, value: h.totalRevenue })),
      byOccupancy:   [...comparison].sort((a, b) => b.occupancyRate - a.occupancyRate).map((h, i) => ({ rank: i + 1, hotelId: h.hotelId, value: h.occupancyRate })),
      byMargin:      [...comparison].sort((a, b) => b.grossMargin - a.grossMargin).map((h, i) => ({ rank: i + 1, hotelId: h.hotelId, value: h.grossMargin })),
    };

    res.json({ period: { start, end }, groupId, comparison, ranked });
  } catch (err) {
    console.error('Hotel compare error:', err);
    res.status(500).json({ error: 'Failed to generate hotel comparison' });
  }
});

/**
 * GET /reports/group/revenue-trend
 * Daily/weekly/monthly revenue trend for each hotel, aggregated over the group.
 */
router.get('/group/revenue-trend', authenticate, requireLevel(8), async (req, res) => {
  try {
    const { period, startDate, endDate, groupBy = 'day' } = req.query;
    const groupId  = resolveGroupId(req.user, req.query.groupId);
    const { start, end } = resolvePeriod(period, startDate, endDate);

    const hotels = await prisma.hotel.findMany({
      where: { ...(groupId ? { groupId } : {}), isActive: true },
      select: { id: true, name: true },
    });
    const hotelIds = hotels.map((h) => h.id);

    const transactions = await prisma.transaction.findMany({
      where: { hotelId: { in: hotelIds }, createdAt: { gte: start, lte: end } },
      select: { hotelId: true, type: true, amount: true, createdAt: true },
      orderBy: { createdAt: 'asc' },
    });

    // Build [{ date, hotelId, hotelName, income, expense, net }]
    const hotelMap = Object.fromEntries(hotels.map((h) => [h.id, h.name]));
    const trendMap = {};

    transactions.forEach((t) => {
      const key = `${formatDateKey(new Date(t.createdAt), groupBy)}__${t.hotelId}`;
      if (!trendMap[key]) trendMap[key] = { date: formatDateKey(new Date(t.createdAt), groupBy), hotelId: t.hotelId, hotelName: hotelMap[t.hotelId], income: 0, expense: 0, net: 0 };
      if (t.type === 'INCOME') trendMap[key].income += Number(t.amount);
      else                      trendMap[key].expense += Number(t.amount);
      trendMap[key].net = trendMap[key].income - trendMap[key].expense;
    });

    // Also compute group-level aggregate per date
    const groupTrend = {};
    Object.values(trendMap).forEach((row) => {
      if (!groupTrend[row.date]) groupTrend[row.date] = { date: row.date, income: 0, expense: 0, net: 0 };
      groupTrend[row.date].income  += row.income;
      groupTrend[row.date].expense += row.expense;
      groupTrend[row.date].net     += row.net;
    });

    res.json({
      period:     { start, end },
      groupBy,
      groupId,
      hotels:     hotels.map((h) => ({ id: h.id, name: h.name })),
      byHotel:    Object.values(trendMap).sort((a, b) => a.date.localeCompare(b.date)),
      groupTrend: Object.values(groupTrend).sort((a, b) => a.date.localeCompare(b.date)),
    });
  } catch (err) {
    console.error('Revenue trend error:', err);
    res.status(500).json({ error: 'Failed to generate revenue trend' });
  }
});

/**
 * GET /reports/group/staff-activity
 * Staff headcount, verified status, role distribution, and recent activity per hotel.
 */
router.get('/group/staff-activity', authenticate, requireLevel(8), async (req, res) => {
  try {
    const { period, startDate, endDate } = req.query;
    const groupId  = resolveGroupId(req.user, req.query.groupId);
    const { start, end } = resolvePeriod(period, startDate, endDate);

    const hotels = await prisma.hotel.findMany({
      where: { ...(groupId ? { groupId } : {}), isActive: true },
      select: { id: true, name: true, maxStaff: true },
      orderBy: { name: 'asc' },
    });
    const hotelIds = hotels.map((h) => h.id);
    const dateRange = { gte: start, lte: end };

    const [users, checkInActivity, posActivity, expenseActivity] = await Promise.all([
      prisma.user.findMany({
        where: { hotelId: { in: hotelIds } },
        select: { hotelId: true, role: true, isVerified: true, createdAt: true },
      }),
      prisma.roomLog.groupBy({
        by: ['hotelId', 'createdById'],
        where: { hotelId: { in: hotelIds }, createdAt: dateRange },
        _count: true,
      }),
      prisma.pOSSale.groupBy({
        by: ['hotelId', 'staffId'],
        where: { hotelId: { in: hotelIds }, createdAt: dateRange },
        _count: true,
        _sum: { totalAmount: true },
      }),
      prisma.expense.groupBy({
        by: ['hotelId'],
        where: { hotelId: { in: hotelIds }, createdAt: dateRange },
        _count: true,
      }),
    ]);

    const hotelStats = hotels.map((h) => {
      const hotelUsers  = users.filter((u) => u.hotelId === h.id);
      const byRole      = {};
      hotelUsers.forEach((u) => {
        if (!byRole[u.role]) byRole[u.role] = { total: 0, verified: 0 };
        byRole[u.role].total++;
        if (u.isVerified) byRole[u.role].verified++;
      });
      const checkIns  = checkInActivity.filter((c) => c.hotelId === h.id).reduce((s, c) => s + c._count, 0);
      const posSales  = posActivity.filter((p) => p.hotelId === h.id).reduce((s, p) => s + p._count, 0);
      const posRev    = posActivity.filter((p) => p.hotelId === h.id).reduce((s, p) => s + Number(p._sum?.totalAmount || 0), 0);
      const expenses  = expenseActivity.find((e) => e.hotelId === h.id)?._count || 0;

      return {
        hotelId:      h.id,
        hotelName:    h.name,
        maxStaff:     h.maxStaff,
        totalStaff:   hotelUsers.length,
        verifiedStaff:hotelUsers.filter((u) => u.isVerified).length,
        staffUtilisation: h.maxStaff > 0
          ? Math.round((hotelUsers.length / h.maxStaff) * 100) : 0,
        byRole,
        activity: {
          checkInsProcessed: checkIns,
          posSalesProcessed: posSales,
          posRevenue:        posRev,
          expensesSubmitted: expenses,
        },
      };
    });

    res.json({ period: { start, end }, groupId, hotels: hotelStats });
  } catch (err) {
    console.error('Staff activity error:', err);
    res.status(500).json({ error: 'Failed to generate staff activity report' });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// ── EXCEL EXPORT  (all report types including new group reports) ───────────────
// ═══════════════════════════════════════════════════════════════════════════════

router.get('/export/excel', authenticate, requireLevel(7), async (req, res) => {
  try {
    const {
      type = 'financial', hotelId, period,
      startDate, endDate, year, groupBy = 'day',
    } = req.query;

    const hotelIds = await resolveHotelScope(req.user, hotelId);
    const groupId  = resolveGroupId(req.user, req.query.groupId);
    const { start, end } = resolvePeriod(period, startDate, endDate);

    const wb = new ExcelJS.Workbook();
    wb.creator   = 'Anchor Hotel Suite';
    wb.company   = 'Anchor Hotel Suite';
    wb.created   = new Date();
    wb.modified  = new Date();
    wb.description = `${type} report exported by ${req.user.name} (${req.user.role})`;

    const NAVY_ARG  = 'FF1A3A5C';
    const TEAL_ARG  = 'FF0D9488';
    const LGREY_ARG = 'FFF1F5F9';
    const WHITE_ARG = 'FFFFFFFF';
    const GREEN_ARG = 'FF16A34A';
    const RED_ARG   = 'FFDC2626';

    const hStyle = {
      font:      { bold: true, color: { argb: WHITE_ARG }, size: 10 },
      fill:      { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY_ARG } },
      alignment: { horizontal: 'center', vertical: 'middle', wrapText: true },
      border:    { bottom: { style: 'thin', color: { argb: TEAL_ARG } } },
    };

    /** Add a branded cover/auth sheet as the first worksheet. */
    function addAuthSheet(reportTitle) {
      const auth = wb.addWorksheet('Report Info');
      auth.getColumn('A').width = 28;
      auth.getColumn('B').width = 48;

      const titleRow = auth.addRow([`Anchor Hotel Suite — ${reportTitle}`]);
      titleRow.getCell(1).font  = { bold: true, size: 16, color: { argb: WHITE_ARG } };
      titleRow.getCell(1).fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY_ARG } };
      titleRow.getCell(1).alignment = { horizontal: 'center' };
      auth.mergeCells(`A1:B1`);
      auth.getRow(1).height = 36;

      const subRow = auth.addRow(['Powered by Anchor Hotel Suite']);
      subRow.getCell(1).font  = { bold: true, color: { argb: WHITE_ARG }, size: 9 };
      subRow.getCell(1).fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: TEAL_ARG } };
      subRow.getCell(1).alignment = { horizontal: 'center' };
      auth.mergeCells('A2:B2');

      auth.addRow([]);

      const meta = [
        ['Report Type',    type.replace(/-/g, ' ').toUpperCase()],
        ['Generated By',   `${req.user.name}  (${req.user.role})`],
        ['Hotel / Scope',  hotelId ? hotelId : (groupId ? `Group: ${groupId}` : 'All accessible hotels')],
        ['Period Start',   start.toLocaleDateString('en-NG', { dateStyle: 'full' })],
        ['Period End',     end.toLocaleDateString('en-NG',   { dateStyle: 'full' })],
        ['Generated At',   new Date().toLocaleString('en-NG')],
        ['Confidential',   'This report is for authorised personnel only.'],
      ];
      meta.forEach(([label, value]) => {
        const r = auth.addRow([label, value]);
        r.getCell(1).font  = { bold: true, color: { argb: NAVY_ARG } };
        r.getCell(1).fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: LGREY_ARG } };
        r.getCell(2).fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: WHITE_ARG } };
        r.getCell(2).font  = { color: { argb: 'FF334155' } };
        r.height = 18;
      });
    }

    // ── Financial ──────────────────────────────────────────────────────────────
    if (type === 'financial') {
      addAuthSheet('Financial Report');
      const where = { hotelId: { in: hotelIds }, createdAt: { gte: start, lte: end } };
      const txns = await prisma.transaction.findMany({
        where, include: { hotel: { select: { name: true } } }, orderBy: { createdAt: 'asc' },
      });
      const sheet = wb.addWorksheet('Financial Report');
      sheet.columns = [
        { header: 'Date',           key: 'date',     width: 20 },
        { header: 'Hotel',          key: 'hotel',    width: 26 },
        { header: 'Type',           key: 'type',     width: 12 },
        { header: 'Category',       key: 'category', width: 18 },
        { header: 'Payment Method', key: 'method',   width: 16 },
        { header: 'Description',    key: 'desc',     width: 34 },
        { header: 'Amount (NGN)',   key: 'amount',   width: 18 },
      ];
      sheet.getRow(1).eachCell((cell) => Object.assign(cell, hStyle));
      txns.forEach((t, i) => {
        const r = sheet.addRow({
          date: new Date(t.createdAt).toLocaleString('en-NG'),
          hotel: t.hotel?.name || '', type: t.type, category: t.category,
          method: t.paymentMethod, desc: t.description || '', amount: Number(t.amount),
        });
        if (i % 2 === 0) r.eachCell((c) => { c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LGREY_ARG } }; });
        const amtCell = r.getCell('amount');
        amtCell.numFmt = '#,##0.00';
        amtCell.font   = { color: { argb: t.type === 'INCOME' ? GREEN_ARG : RED_ARG } };
      });
      const income  = txns.filter((t) => t.type === 'INCOME').reduce((s, t) => s + Number(t.amount), 0);
      const expense = txns.filter((t) => t.type === 'EXPENSE').reduce((s, t) => s + Number(t.amount), 0);
      sheet.addRow([]);
      [['Total Income', income, GREEN_ARG], ['Total Expenses', expense, RED_ARG], ['Net Revenue', income - expense, income - expense >= 0 ? GREEN_ARG : RED_ARG]].forEach(([label, val, col]) => {
        const r = sheet.addRow({ desc: label, amount: val });
        r.getCell('desc').font = { bold: true, color: { argb: NAVY_ARG } };
        r.getCell('amount').numFmt = '#,##0.00';
        r.getCell('amount').font  = { bold: true, color: { argb: col } };
      });
    }

    // ── Occupancy ──────────────────────────────────────────────────────────────
    else if (type === 'occupancy') {
      addAuthSheet('Occupancy Report');
      const logs = await prisma.roomLog.findMany({
        where: { hotelId: { in: hotelIds }, status: { not: 'CANCELLED' }, createdAt: { gte: start, lte: end } },
        include: { room: { select: { number: true, type: true } }, hotel: { select: { name: true } } },
        orderBy: { checkInDate: 'asc' },
      });
      const sheet = wb.addWorksheet('Occupancy Report');
      sheet.columns = [
        { header: 'Hotel',        key: 'hotel',    width: 26 },
        { header: 'Room',         key: 'room',     width: 10 },
        { header: 'Room Type',    key: 'rtype',    width: 14 },
        { header: 'Guest',        key: 'guest',    width: 26 },
        { header: 'Check-In',     key: 'checkIn',  width: 18 },
        { header: 'Check-Out',    key: 'checkOut', width: 18 },
        { header: 'Nights',       key: 'nights',   width: 10 },
        { header: 'Total (NGN)',  key: 'total',    width: 18 },
        { header: 'Paid (NGN)',   key: 'paid',     width: 18 },
        { header: 'Balance (NGN)',key: 'balance',  width: 18 },
        { header: 'Status',       key: 'status',   width: 14 },
      ];
      sheet.getRow(1).eachCell((cell) => Object.assign(cell, hStyle));
      logs.forEach((l, i) => {
        const r = sheet.addRow({
          hotel: l.hotel?.name || '', room: l.room?.number || '', rtype: l.room?.type || '',
          guest: l.guestName, checkIn: new Date(l.checkInDate).toLocaleDateString('en-NG'),
          checkOut: new Date(l.checkOutDate).toLocaleDateString('en-NG'),
          nights: l.nights, total: Number(l.totalAmount), paid: Number(l.amountPaid),
          balance: Number(l.balance), status: l.status,
        });
        if (i % 2 === 0) r.eachCell((c) => { c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LGREY_ARG } }; });
        ['total','paid','balance'].forEach((k) => { r.getCell(k).numFmt = '#,##0.00'; });
      });
    }

    // ── Monthly Balance ────────────────────────────────────────────────────────
    else if (type === 'monthly-balance') {
      const targetYear = parseInt(year) || new Date().getUTCFullYear();
      addAuthSheet(`Monthly Balance ${targetYear}`);
      const sheet = wb.addWorksheet(`Balance ${targetYear}`);
      sheet.columns = [
        { header: 'Month',               key: 'month',   width: 16 },
        { header: 'Total Income (NGN)',  key: 'income',  width: 22 },
        { header: 'Total Expenses (NGN)',key: 'expense', width: 22 },
        { header: 'Net Balance (NGN)',   key: 'net',     width: 20 },
      ];
      sheet.getRow(1).eachCell((cell) => Object.assign(cell, hStyle));
      for (let m = 0; m < 12; m++) {
        const s = new Date(Date.UTC(targetYear, m, 1));
        const e = new Date(Date.UTC(targetYear, m + 1, 0, 23, 59, 59, 999));
        const w = { hotelId: { in: hotelIds }, createdAt: { gte: s, lte: e } };
        const [inc, exp] = await Promise.all([
          prisma.transaction.aggregate({ where: { ...w, type: 'INCOME'  }, _sum: { amount: true } }),
          prisma.transaction.aggregate({ where: { ...w, type: 'EXPENSE' }, _sum: { amount: true } }),
        ]);
        const income  = Number(inc._sum.amount || 0);
        const expense = Number(exp._sum.amount || 0);
        const r = sheet.addRow({ month: s.toLocaleString('en', { month: 'long' }), income, expense, net: income - expense });
        if (m % 2 === 0) r.eachCell((c) => { c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LGREY_ARG } }; });
        ['income','expense','net'].forEach((k) => { r.getCell(k).numFmt = '#,##0.00'; });
        r.getCell('net').font = { color: { argb: income - expense >= 0 ? GREEN_ARG : RED_ARG } };
      }
    }

    // ── POS Summary ────────────────────────────────────────────────────────────
    else if (type === 'pos-summary') {
      addAuthSheet('POS Sales Report');
      const sales = await prisma.pOSSale.findMany({
        where: { hotelId: { in: hotelIds }, createdAt: { gte: start, lte: end } },
        include: { items: true, hotel: { select: { name: true } }, staff: { select: { name: true } } },
        orderBy: { createdAt: 'asc' },
      });
      const sheet = wb.addWorksheet('POS Sales');
      sheet.columns = [
        { header: 'Date',       key: 'date',    width: 20 },
        { header: 'Hotel',      key: 'hotel',   width: 26 },
        { header: 'Staff',      key: 'staff',   width: 20 },
        { header: 'Item',       key: 'item',    width: 26 },
        { header: 'Category',   key: 'cat',     width: 16 },
        { header: 'Qty',        key: 'qty',     width: 8  },
        { header: 'Unit Price', key: 'unit',    width: 14 },
        { header: 'Total',      key: 'total',   width: 14 },
        { header: 'Payment',    key: 'payment', width: 14 },
      ];
      sheet.getRow(1).eachCell((cell) => Object.assign(cell, hStyle));
      let i = 0;
      sales.forEach((sale) => {
        sale.items.forEach((item) => {
          const r = sheet.addRow({
            date: new Date(sale.createdAt).toLocaleString('en-NG'),
            hotel: sale.hotel?.name || '', staff: sale.staff?.name || '',
            item: item.name, cat: item.category, qty: item.quantity,
            unit: Number(item.unitPrice), total: Number(item.totalPrice), payment: sale.paymentType,
          });
          if (i % 2 === 0) r.eachCell((c) => { c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LGREY_ARG } }; });
          ['unit','total'].forEach((k) => { r.getCell(k).numFmt = '#,##0.00'; });
          i++;
        });
      });
    }

    // ── Group Performance ──────────────────────────────────────────────────────
    else if (type === 'group-performance') {
      addAuthSheet('Group Performance Report');

      const hotels = await prisma.hotel.findMany({
        where: { ...(groupId ? { groupId } : { id: { in: hotelIds } }), isActive: true },
        select: { id: true, name: true, totalRooms: true },
        orderBy: { name: 'asc' },
      });
      const hIds = hotels.map((h) => h.id);
      const dr   = { gte: start, lte: end };

      const [rev, exp, ci, nights, pos] = await Promise.all([
        prisma.transaction.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, type: 'INCOME',  createdAt: dr }, _sum: { amount: true } }),
        prisma.transaction.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, type: 'EXPENSE', createdAt: dr }, _sum: { amount: true } }),
        prisma.roomLog.groupBy({     by: ['hotelId'], where: { hotelId: { in: hIds }, status: { not: 'CANCELLED' }, createdAt: dr }, _count: true }),
        prisma.roomLog.groupBy({     by: ['hotelId'], where: { hotelId: { in: hIds }, status: { not: 'CANCELLED' }, createdAt: dr }, _sum: { nights: true } }),
        prisma.pOSSale.groupBy({     by: ['hotelId'], where: { hotelId: { in: hIds }, createdAt: dr }, _sum: { totalAmount: true } }),
      ]);

      const ri = Object.fromEntries(rev.map((r) => [r.hotelId, Number(r._sum?.amount || 0)]));
      const ei = Object.fromEntries(exp.map((r) => [r.hotelId, Number(r._sum?.amount || 0)]));
      const cii= Object.fromEntries(ci.map((r)  => [r.hotelId, r._count]));
      const ni = Object.fromEntries(nights.map((r) => [r.hotelId, Number(r._sum?.nights || 0)]));
      const pi = Object.fromEntries(pos.map((r) => [r.hotelId, Number(r._sum?.totalAmount || 0)]));

      const sheet = wb.addWorksheet('Group Performance');
      sheet.columns = [
        { header: 'Hotel',           key: 'hotel',    width: 28 },
        { header: 'Total Revenue',   key: 'revenue',  width: 20 },
        { header: 'Total Expenses',  key: 'expenses', width: 20 },
        { header: 'Net Profit',      key: 'profit',   width: 18 },
        { header: 'Gross Margin %',  key: 'margin',   width: 16 },
        { header: 'Check-Ins',       key: 'checkins', width: 12 },
        { header: 'Total Nights',    key: 'nights',   width: 14 },
        { header: 'Occ. Rate %',     key: 'occ',      width: 14 },
        { header: 'POS Revenue',     key: 'pos',      width: 18 },
      ];
      sheet.getRow(1).eachCell((cell) => Object.assign(cell, hStyle));

      let totRev = 0, totExp = 0, totCI = 0;
      hotels.forEach((h, idx) => {
        const revenue  = ri[h.id] || 0;
        const expenses = ei[h.id] || 0;
        const profit   = revenue - expenses;
        const margin   = revenue > 0 ? Math.round((profit / revenue) * 100) : 0;
        const nights   = ni[h.id] || 0;
        const occ      = h.totalRooms > 0 && nights > 0 ? Math.min(100, Math.round((nights / (h.totalRooms * 30)) * 100)) : 0;
        totRev += revenue; totExp += expenses; totCI += cii[h.id] || 0;

        const r = sheet.addRow({ hotel: h.name, revenue, expenses, profit, margin, checkins: cii[h.id] || 0, nights, occ, pos: pi[h.id] || 0 });
        if (idx % 2 === 0) r.eachCell((c) => { c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LGREY_ARG } }; });
        ['revenue','expenses','profit','pos'].forEach((k) => { r.getCell(k).numFmt = '#,##0.00'; });
        r.getCell('profit').font = { color: { argb: profit >= 0 ? GREEN_ARG : RED_ARG } };
        r.getCell('margin').numFmt = '0"%"';
      });

      // Totals row
      sheet.addRow([]);
      const totRow = sheet.addRow({ hotel: 'GROUP TOTAL', revenue: totRev, expenses: totExp, profit: totRev - totExp, margin: totRev > 0 ? Math.round(((totRev - totExp) / totRev) * 100) : 0, checkins: totCI });
      totRow.eachCell((c) => { c.font = { bold: true, color: { argb: WHITE_ARG } }; c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY_ARG } }; });
      ['revenue','expenses','profit','pos'].forEach((k) => { totRow.getCell(k).numFmt = '#,##0.00'; });
    }

    // ── Group Hotel Compare ────────────────────────────────────────────────────
    else if (type === 'group-hotel-compare') {
      addAuthSheet('Hotel Comparison Report');
      // Re-use the hotel-compare data
      const hotels = await prisma.hotel.findMany({
        where: { ...(groupId ? { groupId } : { id: { in: hotelIds } }), isActive: true },
        select: { id: true, name: true, totalRooms: true },
        orderBy: { name: 'asc' },
      });
      const hIds = hotels.map((h) => h.id);
      const dr   = { gte: start, lte: end };

      const [rev, exps, bk, posR] = await Promise.all([
        prisma.transaction.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, type: 'INCOME',  createdAt: dr }, _sum: { amount: true } }),
        prisma.transaction.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, type: 'EXPENSE', createdAt: dr }, _sum: { amount: true } }),
        prisma.roomLog.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, status: { not: 'CANCELLED' }, createdAt: dr }, _count: true, _avg: { totalAmount: true }, _sum: { nights: true } }),
        prisma.pOSSale.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, createdAt: dr }, _sum: { totalAmount: true }, _count: true }),
      ]);
      const ri2 = Object.fromEntries(rev.map((r) => [r.hotelId, r]));
      const ei2 = Object.fromEntries(exps.map((r) => [r.hotelId, r]));
      const bi2 = Object.fromEntries(bk.map((r) => [r.hotelId, r]));
      const pi2 = Object.fromEntries(posR.map((r) => [r.hotelId, r]));

      // Revenue rank sheet
      const rankSheet = wb.addWorksheet('Revenue Ranking');
      rankSheet.columns = [
        { header: 'Rank', key: 'rank', width: 8 },
        { header: 'Hotel', key: 'hotel', width: 28 },
        { header: 'Revenue (NGN)', key: 'revenue', width: 20 },
        { header: 'Net Profit (NGN)', key: 'profit', width: 20 },
        { header: 'Margin %', key: 'margin', width: 14 },
        { header: 'Check-Ins', key: 'ci', width: 12 },
        { header: 'Avg Booking (NGN)', key: 'avgbk', width: 20 },
        { header: 'POS Revenue (NGN)', key: 'pos', width: 20 },
        { header: 'Rev/Room (NGN)', key: 'rpr', width: 18 },
      ];
      rankSheet.getRow(1).eachCell((cell) => Object.assign(cell, hStyle));

      const rows = hotels.map((h) => {
        const revenue = Number(ri2[h.id]?._sum?.amount || 0);
        const expense = Number(ei2[h.id]?._sum?.amount || 0);
        const profit  = revenue - expense;
        const margin  = revenue > 0 ? Math.round((profit / revenue) * 100) : 0;
        const ci      = bi2[h.id]?._count || 0;
        const avgBk   = ci > 0 ? Math.round(Number(bi2[h.id]?._avg?.totalAmount || 0)) : 0;
        const pos     = Number(pi2[h.id]?._sum?.totalAmount || 0);
        const rpr     = h.totalRooms > 0 ? Math.round(revenue / h.totalRooms) : 0;
        return { hotel: h.name, revenue, profit, margin, ci, avgBk: avgBk, pos, rpr };
      }).sort((a, b) => b.revenue - a.revenue);

      rows.forEach((row, i) => {
        const r = rankSheet.addRow({ rank: i + 1, hotel: row.hotel, revenue: row.revenue, profit: row.profit, margin: row.margin, ci: row.ci, avgbk: row.avgBk, pos: row.pos, rpr: row.rpr });
        if (i % 2 === 0) r.eachCell((c) => { c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LGREY_ARG } }; });
        ['revenue','profit','avgbk','pos','rpr'].forEach((k) => { r.getCell(k).numFmt = '#,##0.00'; });
        r.getCell('profit').font = { color: { argb: row.profit >= 0 ? GREEN_ARG : RED_ARG } };
        if (i === 0) r.getCell('rank').font = { bold: true, color: { argb: 'FFFFD700' } }; // gold for #1
      });
    }

    else {
      return res.status(400).json({ error: `Unknown report type: ${type}. Valid types: financial, occupancy, monthly-balance, pos-summary, group-performance, group-hotel-compare` });
    }

    const safeType = type.replace(/[^a-z0-9-]/gi, '-');
    const filename = `anchor-${safeType}-${start.toISOString().slice(0, 10)}_to_${end.toISOString().slice(0, 10)}.xlsx`;
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    await wb.xlsx.write(res);
    res.end();
  } catch (err) {
    console.error('Excel export error:', err);
    res.status(500).json({ error: 'Failed to export Excel report' });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// ── PDF EXPORT  (branded, all report types) ────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * GET /reports/export/pdf?type=...&period=...&startDate=...&endDate=...
 *
 * Streams a fully branded PDF:
 *  • Cover page  : Anchor Hotel Suite logo block, report title, period, generated-by auth stamp
 *  • Data pages  : Tables with navy headers, alternating row shading
 *  • Every page footer: "Powered by Anchor Hotel Suite" + page number
 */
router.get('/export/pdf', authenticate, requireLevel(7), async (req, res) => {
  try {
    const { type = 'financial', hotelId, period, startDate, endDate, year, groupBy = 'day' } = req.query;
    const hotelIds = await resolveHotelScope(req.user, hotelId);
    const groupId  = resolveGroupId(req.user, req.query.groupId);
    const { start, end } = resolvePeriod(period, startDate, endDate);

    // ── Collect data based on type ────────────────────────────────────────────
    let reportData = null;
    let reportTitle = '';

    if (type === 'financial') {
      reportTitle = 'Financial Report';
      const where = { hotelId: { in: hotelIds }, createdAt: { gte: start, lte: end } };
      const txns = await prisma.transaction.findMany({
        where, include: { hotel: { select: { name: true } } }, orderBy: { createdAt: 'asc' },
      });
      const income  = txns.filter((t) => t.type === 'INCOME').reduce((s, t) => s + Number(t.amount), 0);
      const expense = txns.filter((t) => t.type === 'EXPENSE').reduce((s, t) => s + Number(t.amount), 0);
      reportData = { type, txns, income, expense };
    }

    else if (type === 'group-performance' || type === 'group-hotel-compare') {
      reportTitle = type === 'group-performance' ? 'Group Performance Report' : 'Hotel Comparison Report';
      const hotels = await prisma.hotel.findMany({
        where: { ...(groupId ? { groupId } : { id: { in: hotelIds } }), isActive: true },
        select: { id: true, name: true, totalRooms: true },
        orderBy: { name: 'asc' },
      });
      const hIds = hotels.map((h) => h.id);
      const dr   = { gte: start, lte: end };
      const [rev, exps, ci, nights, posRev] = await Promise.all([
        prisma.transaction.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, type: 'INCOME',  createdAt: dr }, _sum: { amount: true } }),
        prisma.transaction.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, type: 'EXPENSE', createdAt: dr }, _sum: { amount: true } }),
        prisma.roomLog.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, status: { not: 'CANCELLED' }, createdAt: dr }, _count: true }),
        prisma.roomLog.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, status: { not: 'CANCELLED' }, createdAt: dr }, _sum: { nights: true } }),
        prisma.pOSSale.groupBy({ by: ['hotelId'], where: { hotelId: { in: hIds }, createdAt: dr }, _sum: { totalAmount: true } }),
      ]);
      const ri = Object.fromEntries(rev.map((r) => [r.hotelId, Number(r._sum?.amount || 0)]));
      const ei = Object.fromEntries(exps.map((r) => [r.hotelId, Number(r._sum?.amount || 0)]));
      const cii= Object.fromEntries(ci.map((r) => [r.hotelId, r._count]));
      const ni = Object.fromEntries(nights.map((r) => [r.hotelId, Number(r._sum?.nights || 0)]));
      const pi = Object.fromEntries(posRev.map((r) => [r.hotelId, Number(r._sum?.totalAmount || 0)]));
      const hotelStats = hotels.map((h) => {
        const revenue = ri[h.id] || 0;
        const expense = ei[h.id] || 0;
        const nightsCount = ni[h.id] || 0;
        const occ = h.totalRooms > 0 && nightsCount > 0 ? Math.min(100, Math.round((nightsCount / (h.totalRooms * 30)) * 100)) : 0;
        return { name: h.name, totalRooms: h.totalRooms, revenue, expense, profit: revenue - expense,
                 margin: revenue > 0 ? Math.round(((revenue - expense) / revenue) * 100) : 0,
                 checkIns: cii[h.id] || 0, nights: nightsCount, occupancyRate: occ, pos: pi[h.id] || 0 };
      });
      const groupTotals = hotelStats.reduce((a, h) => ({
        revenue: a.revenue + h.revenue, expense: a.expense + h.expense,
        profit: a.profit + h.profit, checkIns: a.checkIns + h.checkIns, pos: a.pos + h.pos,
      }), { revenue: 0, expense: 0, profit: 0, checkIns: 0, pos: 0 });
      reportData = { type, hotels: hotelStats, groupTotals };
    }

    else if (type === 'occupancy') {
      reportTitle = 'Occupancy Report';
      const logs = await prisma.roomLog.findMany({
        where: { hotelId: { in: hotelIds }, status: { not: 'CANCELLED' }, createdAt: { gte: start, lte: end } },
        include: { room: { select: { number: true, type: true } }, hotel: { select: { name: true } } },
        orderBy: { checkInDate: 'asc' },
      });
      reportData = { type, logs };
    }

    else if (type === 'pos-summary') {
      reportTitle = 'POS Sales Report';
      const sales = await prisma.pOSSale.findMany({
        where: { hotelId: { in: hotelIds }, createdAt: { gte: start, lte: end } },
        include: { items: true, hotel: { select: { name: true } }, staff: { select: { name: true } } },
        orderBy: { createdAt: 'asc' },
      });
      reportData = { type, sales };
    }

    else {
      return res.status(400).json({ error: `PDF export not supported for type: ${type}. Use: financial, occupancy, pos-summary, group-performance, group-hotel-compare` });
    }

    // ── Build PDF ─────────────────────────────────────────────────────────────
    const safeType = type.replace(/[^a-z0-9-]/gi, '-');
    const filename = `anchor-${safeType}-${start.toISOString().slice(0, 10)}_to_${end.toISOString().slice(0, 10)}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    const doc = buildReportPDF({ reportTitle, reportData, start, end, user: req.user, groupId, type });
    doc.pipe(res);
    doc.end();
  } catch (err) {
    console.error('PDF export error:', err);
    res.status(500).json({ error: 'Failed to export PDF report' });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// PDF BUILDER
// ═══════════════════════════════════════════════════════════════════════════════

function buildReportPDF({ reportTitle, reportData, start, end, user, groupId, type }) {
  const doc = new PDFDocument({
    size:    'A4',
    margins: { top: 50, bottom: 60, left: 40, right: 40 },
    bufferPages: true,
    info: {
      Title:    `Anchor Hotel Suite — ${reportTitle}`,
      Author:   user.name,
      Creator:  'Anchor Hotel Suite',
      Subject:  `${reportTitle} ${start.toLocaleDateString()} – ${end.toLocaleDateString()}`,
    },
  });

  const PW   = doc.page.width  - 80; // usable width
  const ML   = 40;                    // margin left
  let   y    = 50;
  let   pageNum = 1;

  // ── Per-page footer via pdfkit bufferedPages ──────────────────────────────
  function addPageFooters() {
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      const footerY = doc.page.height - 40;
      doc.rect(ML, footerY - 4, PW, 0.5).fill(C.mgrey);
      doc.fontSize(7).font('Helvetica').fillColor(C.mgrey)
         .text(`Generated by ${user.name}  •  ${user.role}  •  ${new Date().toLocaleString('en-NG')}`,
               ML, footerY + 2, { width: PW * 0.65 });
      doc.fontSize(7).font('Helvetica-Bold').fillColor(C.teal)
         .text('Powered by Anchor Hotel Suite', ML, footerY + 2, { width: PW, align: 'right' });
      doc.fontSize(7).fillColor(C.mgrey)
         .text(`Page ${i - range.start + 1} of ${range.count}`, ML, footerY + 12, { width: PW, align: 'center' });
    }
  }

  // ── COVER PAGE ────────────────────────────────────────────────────────────
  // Full-width navy header
  doc.rect(0, 0, doc.page.width, 180).fill(C.navy);

  // Brand name
  doc.fontSize(28).font('Helvetica-Bold').fillColor(C.white)
     .text('ANCHOR', ML, 40, { continued: true })
     .fillColor(C.teal).text(' HOTEL SUITE');

  doc.fontSize(11).font('Helvetica').fillColor('#93C5FD')
     .text('Group Management Platform', ML, 80);

  // Teal accent bar
  doc.rect(ML, 105, 60, 4).fill(C.teal);

  // Report title on cover
  doc.fontSize(22).font('Helvetica-Bold').fillColor(C.white)
     .text(reportTitle, ML, 118);

  doc.fontSize(11).font('Helvetica').fillColor('#CBD5E1')
     .text(`${start.toLocaleDateString('en-NG', { dateStyle: 'long' })}  —  ${end.toLocaleDateString('en-NG', { dateStyle: 'long' })}`, ML, 148);

  // Auth block on cover
  y = 210;
  doc.rect(ML, y, PW, 120).fill(C.lgrey);
  doc.rect(ML, y, 4, 120).fill(C.teal);

  doc.fontSize(8).font('Helvetica-Bold').fillColor(C.navy).text('REPORT AUTHENTICATION', ML + 16, y + 10);

  const authInfo = [
    ['Generated By', `${user.name}  (${user.role})`],
    ['Scope',        groupId ? `Group ID: ${groupId}` : 'All accessible hotels'],
    ['Period',       `${start.toLocaleDateString('en-NG')} to ${end.toLocaleDateString('en-NG')}`],
    ['Timestamp',    new Date().toLocaleString('en-NG')],
    ['Confidential', 'For authorised personnel only. Do not distribute.'],
  ];
  authInfo.forEach(([label, value], i) => {
    doc.fontSize(8).font('Helvetica-Bold').fillColor(C.navy)
       .text(label + ':', ML + 16, y + 26 + i * 17, { width: 110, continued: false });
    doc.fontSize(8).font('Helvetica').fillColor(C.dgrey)
       .text(value, ML + 130, y + 26 + i * 17, { width: PW - 130 });
  });

  y = 350;

  // Cover decorative summary (counts)
  if (reportData.type === 'group-performance' || reportData.type === 'group-hotel-compare') {
    const { groupTotals, hotels } = reportData;
    const kpis = [
      { label: 'Hotels', value: String(hotels.length) },
      { label: 'Total Revenue', value: fmtNGN(groupTotals.revenue) },
      { label: 'Net Profit', value: fmtNGN(groupTotals.profit) },
      { label: 'Check-Ins', value: String(groupTotals.checkIns) },
    ];
    const kpiW = PW / kpis.length;
    kpis.forEach((kpi, i) => {
      const kx = ML + i * kpiW;
      doc.rect(kx + 4, y, kpiW - 8, 70).fill(C.navy);
      doc.fontSize(11).font('Helvetica-Bold').fillColor(C.teal)
         .text(kpi.value, kx + 4, y + 12, { width: kpiW - 8, align: 'center' });
      doc.fontSize(8).font('Helvetica').fillColor(C.mgrey)
         .text(kpi.label, kx + 4, y + 42, { width: kpiW - 8, align: 'center' });
    });
    y += 86;
  }

  // Powered by on cover bottom
  doc.rect(ML, doc.page.height - 80, PW, 30).fill(C.teal);
  doc.fontSize(10).font('Helvetica-Bold').fillColor(C.white)
     .text('Powered by Anchor Hotel Suite', ML, doc.page.height - 70, { width: PW, align: 'center' });

  // ── DATA PAGES ────────────────────────────────────────────────────────────
  doc.addPage();
  y = 50;

  // Page header
  function pageHeader(title) {
    doc.rect(ML, 20, PW, 24).fill(C.navy);
    doc.fontSize(10).font('Helvetica-Bold').fillColor(C.white)
       .text(title, ML + 10, 28, { width: PW - 80 });
    doc.fontSize(8).font('Helvetica').fillColor(C.teal)
       .text(`${start.toLocaleDateString('en-NG')} – ${end.toLocaleDateString('en-NG')}`, ML, 28, { width: PW, align: 'right' });
  }

  pageHeader(reportTitle);

  // ── Table helper ──────────────────────────────────────────────────────────
  function tableHeader(cols, y) {
    doc.rect(ML, y, PW, 18).fill(C.navy);
    let x = ML + 4;
    cols.forEach((col) => {
      doc.fontSize(7.5).font('Helvetica-Bold').fillColor(C.white)
         .text(col.label, x, y + 5, { width: col.w - 4, align: col.align || 'left' });
      x += col.w;
    });
    return y + 18;
  }

  function tableRow(cols, values, y, shade) {
    if (shade) doc.rect(ML, y, PW, 15).fill(C.lgrey);
    let x = ML + 4;
    cols.forEach((col, i) => {
      const val = values[i] !== undefined && values[i] !== null ? String(values[i]) : '';
      doc.fontSize(7.5).font('Helvetica').fillColor(C.dgrey)
         .text(val, x, y + 4, { width: col.w - 6, align: col.align || 'left', ellipsis: true });
      x += col.w;
    });
    // check if we need a new page
    if (y + 30 > doc.page.height - 70) {
      doc.addPage();
      pageHeader(reportTitle);
      return 56;
    }
    return y + 15;
  }

  function sectionTitle(text, y) {
    doc.rect(ML, y, PW, 16).fill(C.teal);
    doc.fontSize(8.5).font('Helvetica-Bold').fillColor(C.white)
       .text(text, ML + 8, y + 4);
    return y + 22;
  }

  // ── FINANCIAL ─────────────────────────────────────────────────────────────
  if (reportData.type === 'financial') {
    const { txns, income, expense } = reportData;

    // KPI strip
    const kpiY = y + 4;
    [
      { label: 'Total Income', value: fmtNGN(income),          color: C.green },
      { label: 'Total Expenses', value: fmtNGN(expense),       color: C.red   },
      { label: 'Net Revenue',  value: fmtNGN(income - expense),color: income - expense >= 0 ? C.green : C.red },
      { label: 'Transactions', value: String(txns.length),     color: C.navy  },
    ].forEach((kpi, i) => {
      const kx = ML + (PW / 4) * i;
      doc.rect(kx + 2, kpiY, PW / 4 - 4, 44).fill(C.lgrey);
      doc.rect(kx + 2, kpiY, 3, 44).fill(kpi.color);
      doc.fontSize(9).font('Helvetica-Bold').fillColor(kpi.color)
         .text(kpi.value, kx + 10, kpiY + 8, { width: PW / 4 - 16 });
      doc.fontSize(7).font('Helvetica').fillColor(C.mgrey)
         .text(kpi.label, kx + 10, kpiY + 28, { width: PW / 4 - 16 });
    });
    y = kpiY + 54;

    y = sectionTitle('Transaction Detail', y);
    const cols = [
      { label: 'Date',        w: 80 },
      { label: 'Hotel',       w: 90 },
      { label: 'Category',    w: 70 },
      { label: 'Type',        w: 50 },
      { label: 'Method',      w: 60 },
      { label: 'Amount (NGN)',w: PW - 350, align: 'right' },
    ];
    y = tableHeader(cols, y);
    txns.slice(0, 300).forEach((t, i) => {
      y = tableRow(cols, [
        new Date(t.createdAt).toLocaleDateString('en-NG'),
        t.hotel?.name || '', t.category, t.type, t.paymentMethod,
        Number(t.amount).toLocaleString('en-NG', { minimumFractionDigits: 2 }),
      ], y, i % 2 === 0);
    });
    if (txns.length > 300) {
      doc.fontSize(7).fillColor(C.mgrey).text(`... and ${txns.length - 300} more rows. Export to Excel for the full dataset.`, ML, y + 4);
    }
  }

  // ── GROUP PERFORMANCE / COMPARE ───────────────────────────────────────────
  else if (reportData.type === 'group-performance' || reportData.type === 'group-hotel-compare') {
    const { hotels: hs, groupTotals } = reportData;

    y = sectionTitle('Hotel-by-Hotel Performance', y);
    const cols = [
      { label: 'Hotel',       w: 100 },
      { label: 'Revenue',     w: 75, align: 'right' },
      { label: 'Expenses',    w: 75, align: 'right' },
      { label: 'Net Profit',  w: 75, align: 'right' },
      { label: 'Margin %',    w: 50, align: 'right' },
      { label: 'Check-Ins',   w: 50, align: 'right' },
      { label: 'Occ. %',      w: PW - 425, align: 'right' },
    ];
    y = tableHeader(cols, y);
    hs.forEach((h, i) => {
      y = tableRow(cols, [
        h.name,
        Number(h.revenue).toLocaleString('en-NG', { minimumFractionDigits: 0 }),
        Number(h.expense).toLocaleString('en-NG', { minimumFractionDigits: 0 }),
        Number(h.profit).toLocaleString('en-NG', { minimumFractionDigits: 0 }),
        h.margin + '%',
        h.checkIns,
        h.occupancyRate + '%',
      ], y, i % 2 === 0);
    });

    // Totals row
    doc.rect(ML, y, PW, 18).fill(C.navy);
    doc.fontSize(8).font('Helvetica-Bold').fillColor(C.white)
       .text('GROUP TOTAL', ML + 4, y + 5, { width: 100 });
    doc.text(Number(groupTotals.revenue).toLocaleString('en-NG', { minimumFractionDigits: 0 }), ML + 4 + 100, y + 5, { width: 75, align: 'right' });
    doc.text(Number(groupTotals.expense).toLocaleString('en-NG', { minimumFractionDigits: 0 }), ML + 4 + 175, y + 5, { width: 75, align: 'right' });
    doc.text(Number(groupTotals.profit).toLocaleString('en-NG',  { minimumFractionDigits: 0 }), ML + 4 + 250, y + 5, { width: 75, align: 'right' });
    y += 26;
  }

  // ── OCCUPANCY ─────────────────────────────────────────────────────────────
  else if (reportData.type === 'occupancy') {
    const { logs } = reportData;
    y = sectionTitle('Guest Stay Records', y);
    const cols = [
      { label: 'Hotel',     w: 85 },
      { label: 'Room',      w: 40 },
      { label: 'Guest',     w: 90 },
      { label: 'Check-In',  w: 65 },
      { label: 'Check-Out', w: 65 },
      { label: 'Nts',       w: 28 },
      { label: 'Total',     w: 65, align: 'right' },
      { label: 'Status',    w: PW - 438, align: 'center' },
    ];
    y = tableHeader(cols, y);
    logs.slice(0, 300).forEach((l, i) => {
      y = tableRow(cols, [
        l.hotel?.name || '', l.room?.number || '', l.guestName,
        new Date(l.checkInDate).toLocaleDateString('en-NG'),
        new Date(l.checkOutDate).toLocaleDateString('en-NG'),
        l.nights, Number(l.totalAmount).toLocaleString('en-NG', { minimumFractionDigits: 0 }),
        l.status,
      ], y, i % 2 === 0);
    });
  }

  // ── POS SUMMARY ───────────────────────────────────────────────────────────
  else if (reportData.type === 'pos-summary') {
    const { sales } = reportData;
    const grandTotal = sales.reduce((s, x) => s + Number(x.totalAmount), 0);

    doc.rect(ML, y + 4, PW, 36).fill(C.lgrey);
    doc.rect(ML, y + 4, 4, 36).fill(C.teal);
    doc.fontSize(11).font('Helvetica-Bold').fillColor(C.teal)
       .text(fmtNGN(grandTotal), ML + 16, y + 10);
    doc.fontSize(7.5).font('Helvetica').fillColor(C.mgrey)
       .text('Total POS Revenue', ML + 16, y + 28);
    doc.fontSize(9).font('Helvetica-Bold').fillColor(C.navy)
       .text(String(sales.length) + ' sales', ML + PW - 80, y + 16);
    y += 52;

    y = sectionTitle('Sales Detail', y);
    const cols = [
      { label: 'Date',     w: 75 },
      { label: 'Hotel',    w: 85 },
      { label: 'Staff',    w: 70 },
      { label: 'Item',     w: 90 },
      { label: 'Cat.',     w: 55 },
      { label: 'Qty',      w: 28, align: 'right' },
      { label: 'Total',    w: PW - 403, align: 'right' },
    ];
    y = tableHeader(cols, y);
    let rowIdx = 0;
    sales.slice(0, 200).forEach((sale) => {
      sale.items.forEach((item) => {
        y = tableRow(cols, [
          new Date(sale.createdAt).toLocaleDateString('en-NG'),
          sale.hotel?.name || '', sale.staff?.name || '',
          item.name, item.category, item.quantity,
          Number(item.totalPrice).toLocaleString('en-NG', { minimumFractionDigits: 0 }),
        ], y, rowIdx % 2 === 0);
        rowIdx++;
      });
    });
  }

  // Flush page footers
  addPageFooters();

  return doc;
}

export default router;

// ── GET /api/reports/night-audit — Daily Z-Report / Night Audit ───────────────
// Closes the business day with a full financial summary.
// Accessible to General Manager and above (level 7+).
router.get('/night-audit', authenticate, requireLevel(7), async (req, res) => {
  try {
    const { hotelId, date } = req.query;

    // Default to today Lagos time
    const auditDate = date ? new Date(date) : new Date(
      new Date().toLocaleString('en-US', { timeZone: 'Africa/Lagos' })
    );
    const dayStart = new Date(auditDate);
    dayStart.setHours(0, 0, 0, 0);
    const dayEnd = new Date(auditDate);
    dayEnd.setHours(23, 59, 59, 999);

    // Resolve hotel scope
    let hotelIds = [];
    if (req.user.accessLevel >= 10) {
      if (hotelId) {
        hotelIds = [hotelId];
      } else {
        const hotels = await prisma.hotel.findMany({ select: { id: true } });
        hotelIds = hotels.map(h => h.id);
      }
    } else if (req.user.accessLevel >= 8) {
      const hotels = await prisma.hotel.findMany({
        where: { groupId: req.user.groupId },
        select: { id: true },
      });
      hotelIds = hotels.map(h => h.id);
    } else {
      hotelIds = [req.user.hotelId].filter(Boolean);
    }

    if (hotelIds.length === 0) {
      return res.status(400).json({ error: 'No hotels found for this user' });
    }

    const where = { hotelId: { in: hotelIds }, createdAt: { gte: dayStart, lte: dayEnd } };
    const logWhere = { hotelId: { in: hotelIds }, checkedOutAt: { gte: dayStart, lte: dayEnd }, status: 'CHECKED_OUT' };
    const checkInWhere = { hotelId: { in: hotelIds }, checkInDate: { gte: dayStart, lte: dayEnd } };

    const [
      checkIns,
      checkOuts,
      posSales,
      expenses,
      transactions,
      openRooms,
      hotelDetails,
    ] = await Promise.all([
      // New check-ins today
      prisma.roomLog.findMany({
        where: checkInWhere,
        include: { room: { select: { number: true, type: true } }, createdBy: { select: { name: true } } },
        orderBy: { checkInDate: 'asc' },
      }),
      // Checkouts today
      prisma.roomLog.findMany({
        where: logWhere,
        include: { room: { select: { number: true, type: true } } },
        orderBy: { checkedOutAt: 'asc' },
      }),
      // POS sales today
      prisma.pOSSale.findMany({
        where,
        include: { items: true, staff: { select: { name: true } } },
        orderBy: { createdAt: 'asc' },
      }),
      // Expenses today
      prisma.expense.findMany({
        where: { ...where, status: 'APPROVED' },
        include: { submittedBy: { select: { name: true } } },
        orderBy: { createdAt: 'asc' },
      }),
      // All transactions today
      prisma.transaction.findMany({ where, orderBy: { createdAt: 'asc' } }),
      // Currently open rooms
      prisma.roomLog.findMany({
        where: { hotelId: { in: hotelIds }, status: 'ACTIVE' },
        include: { room: { select: { number: true, type: true } }, },
        orderBy: { checkInDate: 'asc' },
      }),
      // Hotel info
      prisma.hotel.findMany({
        where: { id: { in: hotelIds } },
        select: { id: true, name: true, vatPercent: true, currency: true },
      }),
    ]);

    // ── Financial aggregates ───────────────────────────────────────────────
    const roomRevenue = checkOuts.reduce((s, l) => s + Number(l.amountPaid || 0), 0);
    const posRevenue  = posSales.reduce((s, sale) => s + Number(sale.totalAmount || 0), 0);
    const totalExpenses = expenses.reduce((s, e) => s + Number(e.amount || 0), 0);

    // Break down POS by category
    const posByCategory = {};
    posSales.forEach(sale => {
      sale.items.forEach(item => {
        const cat = item.category || 'OTHER';
        posByCategory[cat] = (posByCategory[cat] || 0) + Number(item.totalPrice);
      });
    });

    // Break down expenses by category
    const expensesByCategory = {};
    expenses.forEach(e => {
      expensesByCategory[e.category] = (expensesByCategory[e.category] || 0) + Number(e.amount);
    });

    // Payment method breakdown (from transactions)
    const byPaymentMethod = {};
    transactions.filter(t => t.type === 'INCOME').forEach(t => {
      byPaymentMethod[t.paymentMethod] = (byPaymentMethod[t.paymentMethod] || 0) + Number(t.amount);
    });

    const grossRevenue = roomRevenue + posRevenue;
    const netRevenue   = grossRevenue - totalExpenses;

    // Outstanding balances (guests still checked in)
    const outstandingBalance = openRooms.reduce((s, l) => s + Number(l.balance || 0), 0);

    res.json({
      auditDate: dayStart.toISOString(),
      generatedAt: new Date().toISOString(),
      generatedBy: { id: req.user.id, name: req.user.name, role: req.user.role },
      hotels: hotelDetails,
      summary: {
        grossRevenue,
        roomRevenue,
        posRevenue,
        totalExpenses,
        netRevenue,
        outstandingBalance,
        checkInsCount:  checkIns.length,
        checkOutsCount: checkOuts.length,
        openRoomsCount: openRooms.length,
        posSalesCount:  posSales.length,
        expensesCount:  expenses.length,
      },
      breakdown: {
        posByCategory,
        expensesByCategory,
        byPaymentMethod,
      },
      detail: {
        checkIns: checkIns.map(l => ({
          id: l.id,
          guestName: l.guestName,
          room: l.room?.number,
          roomType: l.room?.type,
          checkInDate: l.checkInDate,
          checkOutDate: l.checkOutDate,
          ratePerNight: l.ratePerNight,
          totalAmount: l.totalAmount,
          checkedInBy: l.createdBy?.name,
        })),
        checkOuts: checkOuts.map(l => ({
          id: l.id,
          guestName: l.guestName,
          room: l.room?.number,
          checkedOutAt: l.checkedOutAt,
          amountPaid: l.amountPaid,
          balance: l.balance,
        })),
        posSales: posSales.map(s => ({
          id: s.id,
          totalAmount: s.totalAmount,
          paymentType: s.paymentType,
          staffName: s.staff?.name,
          createdAt: s.createdAt,
          itemCount: s.items.length,
        })),
        expenses: expenses.map(e => ({
          id: e.id,
          title: e.title,
          amount: e.amount,
          category: e.category,
          submittedBy: e.submittedBy?.name,
        })),
        openRooms: openRooms.map(l => ({
          id: l.id,
          guestName: l.guestName,
          room: l.room?.number,
          checkInDate: l.checkInDate,
          checkOutDate: l.checkOutDate,
          balance: l.balance,
        })),
      },
    });
  } catch (err) {
    console.error('[Night Audit]', err);
    res.status(500).json({ error: 'Failed to generate night audit report' });
  }
});
